import numpy as np
import pandas as pd


def exclude_channels(data, channels_to_exclude):
	"""This function excludes chosen channels from a dataframe and outputs two dataframes: one with the channels that should not be excluded from the fit and one with the excluded channles.
	One will be the input to mske the fit, the other one is just for plotting the excluded channels in gray.

    Args:
        data (pd.DataFrame): the data that you want to fit
        channels_to_exclude (list of integers): a list containing the indices corresponding to the channels you wish to exclude

    Returns:
        list with two pd.DataFrames: first dataframe contains the data to be fit and the second one the excluded channels.
    """
	
	dataframe_to_fit = data
	dataframe_to_exclude = data
	dataframe_to_fit = dataframe_to_fit.drop(channels_to_exclude, axis = 0)
	
	dataframe_to_fit = dataframe_to_fit.reset_index()
	
	channels_to_keep = []
	for i in range(len(data)):
		channels_to_keep.append(i)
	for j in channels_to_exclude:
		channels_to_keep.remove(j)
	
	dataframe_to_exclude = dataframe_to_exclude.drop(channels_to_keep, axis = 0)
	dataframe_to_exclude = dataframe_to_exclude.reset_index()
	return [dataframe_to_fit, dataframe_to_exclude]# return two dataframes. one is the dataframe that will be fit and one will be the one plotted in gray that has the excluded channels.
    

def print_results(file_with_fit_results):
	"""prints the fit results

	Args:
		file_with_fit_results (pd.DataFrame): a dataframe (read from csv) that contains the fit results. This file is automatically generated when running the fit.

	Returns:
		_prints out all values depending on the final fit
	"""
	results = file_with_fit_results
   
	fit_type = ''
	if results['Final fit type'][0] == 'single':
		fit_type = 'single power-law'
		
	if results['Final fit type'][0] == 'double':
		fit_type = 'double power-law'
		
	if results['Final fit type'][0] == 'cut':
		fit_type = 'single power-law with exponential cutoff'
		
	if results['Final fit type'][0] == 'double_cut':
		fit_type = 'double power-law with exponential cutoff'
		
	if results['Final fit type'][0] == 'triple':
		fit_type = 'triple power-law'
		
			
	print('The fit produced the following results:')
	print('Final fit type: ', fit_type)
	print(r'χ²:  ', round(results['Reduced chi sq'][0], ndigits = 2))
	print('Intensity at 100 keV :', round(results['c1'][0], ndigits = 2), r'+/-', round(results['c1 err'][0], ndigits = 2))
	print(r'γ 1:  ', round(results['Gamma1'][0], ndigits = 2), r'+/-', round(results['Gamma1 err'][0], ndigits = 2))

	if fit_type == 'double power-law' or fit_type == 'double power-law with exponential cutoff' or fit_type == 'triple power-law':
		print(r'γ 2:  ', round(results['Gamma2'][0], ndigits = 2), r'+/-', round(results['Gamma2 err'][0], ndigits = 2))
		if fit_type == 'triple power-law':
			print(r'γ 3:  ', round(results['Gamma3'][0], ndigits = 2), r'+/-', round(results['Gamma3 err'][0], ndigits = 2))
		print('Break energy (low) [MeV]:  ', round(results[ 'Break point 1 [MeV]'][0], ndigits = 2), r'+/-', round(results[ 'Break point 1 err [MeV]'][0], ndigits = 2))
		if fit_type == 'triple power-law':
			print('Break energy (high) [MeV]:  ', round(results[ 'Break point 2 [MeV]'][0], ndigits = 2), r'+/-', round(results[ 'Break point 2 err [MeV]'][0], ndigits = 2))
		print('Alpha:  ', round(results[ 'Alpha'][0], ndigits = 2))
		if fit_type == 'triple power-law':
			print('Beta:  ', round(results[ 'Beta'][0], ndigits = 2))

	if fit_type == 'single power-law with exponential cutoff' or fit_type == 'double power-law with exponential cutoff':
		print('Exponential cutoff energy [MeV]:  ', round(results[ 'Exponential cutoff point [MeV]',][0], ndigits = 2), r'+/-', round(results[  'Cutoff err [MeV]'][0], ndigits = 2))
		print('Cutoff exponent:  ', round(results[ 'Exponenent',][0], ndigits = 2))
		
	
	print('E min [MeV]:  ', round(results['E min [MeV]'][0], ndigits = 2))    
	print('E max [MeV]:  ', round(results['E max [MeV]'][0], ndigits = 2) )
		

	return ''

def plot_spectrum(data):
	x_data = data['Energy'] # energy for spectra
	y_data   = data['Intensity']
	x_err = None
	y_err = None

	if 'E_err' in data:
		x_err  = data['E_err']
	if 'I_err' in data:
		y_err    = data['I_err'] 
	if x_err.isnull().all():
		x_err = None
	if y_err.isnull().all():
	    y_err = None
		
	f, ax = plt.subplots(1, figsize=(5, 4), dpi = 300)
		
	ax.errorbar(x_data, y_data, xerr = x_err, yerr=y_err, marker='o', markersize= 3 , linestyle='', color='red', alpha = 0.5, label='data points', zorder = -1)
    
	x_range_min = min(data['Energy'])
	x_range_max = max(data['Energy'])

	ax.set_xlim(x_range_min-(x_range_min/2), x_range_max+(x_range_max/2))
	locmin = pltt.LogLocator(base=10.0,subs=(0.2,0.4,0.6,0.8),numticks=12)
        
	ax.yaxis.set_minor_locator(locmin)
	ax.yaxis.set_minor_formatter(pltt.NullFormatter())

	ax.set_xscale('log')
	ax.set_yscale('log')

	#plt.legend('',  prop={'size': 7})
	plt.ylabel('Intensity')
	plt.xlabel('Energy')
	#plt.title('Example spectrum')
    
	#if save:
	#   plt.savefig(folder_path+'/'+file_name+'_'+name_string+'_fit-plot_'+which_fit+'.png', dpi=300)
	plt.show()
